site_name: course
site_description: a mvp of a course system.
repo_url: https://github.com/kkuzar/course_mvp
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/kkuzar">kkuzar</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
